# Generated by Django 2.2.28 on 2024-03-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Genre', models.CharField(choices=[('animated', 'Animated'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('documentary', 'Documentary'), ('horror', 'Horror'), ('thriller', 'Thriller')], max_length=20)),
                ('Description', models.CharField(max_length=1000)),
                ('ReleaseDate', models.DateField()),
                ('Director', models.CharField(max_length=50)),
                ('Cast', models.CharField(max_length=100)),
            ],
        ),
    ]
