# Generated by Django 2.2.28 on 2024-03-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0003_auto_20240312_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
