# Generated by Django 2.2.28 on 2024-03-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0004_auto_20240312_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
