# Generated by Django 2.2.28 on 2024-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0005_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
