# Generated by Django 2.2.28 on 2024-03-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0006_auto_20240313_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Likes',
            new_name='likes',
        ),
    ]
