# Generated by Django 2.2.28 on 2024-03-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0007_auto_20240315_1449'),
        ('Film_Review', '0007_watchlist'),
    ]

    operations = [
    ]
