# Generated by Django 2.2.28 on 2024-03-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0008_review_likes'),
        ('Film_Review', '0007_auto_20240315_1449'),
    ]

    operations = [
    ]
