# Generated by Django 2.2.28 on 2024-03-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0009_merge_20240315_1759'),
        ('Film_Review', '0008_merge_20240315_2228'),
    ]

    operations = [
    ]
