# Generated by Django 2.2.28 on 2024-03-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Review', '0010_merge_20240315_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Likes',
            new_name='likes',
        ),
    ]
